# Docker Compose 配置文件
version: '3.8'

services:
  nav-app:
    image: mjjnav:1.1.0
    build: .
    container_name: mjjnav
    ports:
      - "721:721"  # 将容器内部721端口映射到主机721端口
    volumes:
      # 将数据库文件映射到主机，确保数据持久化
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:721/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
