# Docker Compose 配置文件
version: '3.8'

services:
  nav-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # 将数据库文件映射到主机，确保数据持久化
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
